### PR TITLE
149 quiz style how old are you and gender question page

### PR DESCRIPTION
**Pull request by edpe**
https://trello.com/c/OSoevIom/149-quiz-style-how-old-are-you-and-gender-question-page-and-split-the-questions-onto-2-pages-vv-e

### CODE REVIEW

**Comment by rosejbon** [comment]
Looks great Ed. I noticed the back button on the gender identity questions goes to interests not age question. :)

**Comment by edpe** [comment]
> Looks great Ed. I noticed the back button on the gender identity questions goes to interests not age question. :)

good spot thanks @rosejbon

**Review by rosejbon — APPROVED** [review]
🥳

**Comment by marxian** [comment]
#### 📝Changed routes:


| [**/quiz/age**](https://my-best-life-ksziqk7ta-neontribe.vercel.app/quiz/age) | [**/quiz/gender**](https://my-best-life-ksziqk7ta-neontribe.vercel.app/quiz/gender) |
|:-:|:-:|
|<a href="https://my-best-life-ksziqk7ta-neontribe.vercel.app/quiz/age">Screenshot of /quiz/age</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/_Ykt66-bwy3v2Lvw_HJqnSKTUA78qpNy8v21v-PaF7gqEalGXmvA4lHv8AGzpggSns9TvWUPjVaVwjKSzsKMHA.png">(view full size)</a> |<a href="https://my-best-life-ksziqk7ta-neontribe.vercel.app/quiz/gender">Screenshot of /quiz/gender</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/AV_ok9M0wJ8FoaSxgeDvB6QA0bEGqon9NIjaWLE8LSQeQs95nIJNBWGrchXJEfGr2-QX8qK7vB2_RcqOPW2Ltw.png">(view full size)</a> |



| [**…hat-are-your-interests**](https://my-best-life-ksziqk7ta-neontribe.vercel.app/quiz/what-are-your-interests) |
|:-:|
|<a href="https://my-best-life-ksziqk7ta-neontribe.vercel.app/quiz/what-are-your-interests">Screenshot of /quiz/what-are-your-interests</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/keMMy84mkFMM92nOAPEgSl8RhzsWLOs3I9FFjh3nBwYu9htRkDVy2CYlMoIW_sJZ6iLga7Ven-xFu3Ei0MzVow.png">(view full size)</a> |







Commit d692013689416594b2913ebb51d8a6d748c63a3b (https://my-best-life-ksziqk7ta-neontribe.vercel.app).

**Review by Nikomus — APPROVED** [review]
Looks good to me 🗝️

**Pull request merged**
