### PR TITLE
feat: move filter button closer to results that use it

### PR DESCRIPTION
**Pull request by Nikomus**
https://trello.com/c/pR1eeDZa/92-make-the-filter-and-results-feel-more-connected-v-e

TODO: Use SVG arrows rather than '<' consistently

### CODE REVIEW

**Comment by jthistle** [comment]
This seems to break the navigation button styling:

Screenshot from 2021-03-29 14-51-19

**Comment by Nikomus** [comment]
@jthistle I can't make it do this.. do you have any hints?

image

**Comment by jthistle** [comment]
Weird... Chromium 84. It renders the svg if I take it and paste it into an about:blank, so the svg is ok.

**Comment by jthistle** [comment]
Hmmm, adding a `width` to the svg fixes it. I don't know why this behaviour is different; perhaps a Chromium bug.

**Comment by Nikomus** [comment]
TY, I'll do that 👍

**Comment by jthistle** [comment]
Oh, and Firefox (latest) does the opposite :sweat_smile: 

Screenshot from 2021-03-30 09-25-28

**Comment by Nikomus** [comment]
@jthistle The Slack built in browser does massive buttons too.. 😬 It should be fixed now.

**Comment by marxian** [comment]
#### 📝Changed routes:


| [**/filter**](https://my-best-life-5qka4k128-neontribe.vercel.app/filter) | [**/**](https://my-best-life-5qka4k128-neontribe.vercel.app/) |
|:-:|:-:|
|<a href="https://my-best-life-5qka4k128-neontribe.vercel.app/filter">Screenshot of /filter</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/Z7rElSaUVxvrcBWSbZvSQrjB_Fs_.png">(view full size)</a> |<a href="https://my-best-life-5qka4k128-neontribe.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/sNzTTCsQijewI5OZHG5eGGJ0CAk_.png">(view full size)</a> |



| [**/quiz/about-you**](https://my-best-life-5qka4k128-neontribe.vercel.app/quiz/about-you) | [**/quiz/how-are-you-feeling**](https://my-best-life-5qka4k128-neontribe.vercel.app/quiz/how-are-you-feeling) |
|:-:|:-:|
|<a href="https://my-best-life-5qka4k128-neontribe.vercel.app/quiz/about-you">Screenshot of /quiz/about-you</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/nNpei_FUZQNDGO3C37IBAid8Vt4_.png">(view full size)</a> |<a href="https://my-best-life-5qka4k128-neontribe.vercel.app/quiz/how-are-you-feeling">Screenshot of /quiz/how-are-you-feeling</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_gifi4SHHNrYiOLAe0N98KUfv44_.png">(view full size)</a> |



| [**…hat-are-your-interests**](https://my-best-life-5qka4k128-neontribe.vercel.app/quiz/what-are-your-interests) | [**/quiz/whats-on-your-mind**](https://my-best-life-5qka4k128-neontribe.vercel.app/quiz/whats-on-your-mind) |
|:-:|:-:|
|<a href="https://my-best-life-5qka4k128-neontribe.vercel.app/quiz/what-are-your-interests">Screenshot of /quiz/what-are-your-interests</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/iAI28MJFdhwFAQp2LXQjJZckZBA_.png">(view full size)</a> |<a href="https://my-best-life-5qka4k128-neontribe.vercel.app/quiz/whats-on-your-mind">Screenshot of /quiz/whats-on-your-mind</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/jwUj08q3LzCr5wf3en92cF3BA1g_.png">(view full size)</a> |



And 1 other route:
- [**/service/\[id\]**](https://my-best-life-5qka4k128-neontribe.vercel.app/service/[id])



Commit 759cf3fd4ba9ed275c6bb4769cb24e69f725fb35 (https://my-best-life-5qka4k128-neontribe.vercel.app).

**Review by jthistle — APPROVED** [review]
All looks great now! And I really like how the nav isn't fighting for attention with the header now :)

**Pull request merged**
