### PR TITLE
feat: add toast notifications

### PR DESCRIPTION
**Pull request by jthistle**
https://trello.com/c/09DHlWsF/

No image for this one, just open up the preview and try it out! Spamming the 'submit review' button is quite fun.

Usage is as simple as:

```jsx
import { useContext } from 'react';
import { NotificationsContext } from './context/NotificationsContext';

const MyComponent = () => {
  const { notify } = useContext(NotificationsContext);
  
  const clickedNotification = () => {
    notify({
      msg: "Hello world!",
      time: 5000,
    });
  };

  return <button onClick={clickedNotification}>Click me!</button>;
}
```

### CODE REVIEW

**Comment by marxian** [comment]
#### 📝Changed routes:


| [**/filter**](https://my-best-life-m0rzfwcau-neontribe.vercel.app/filter) | [**/service/\[id\]**](https://my-best-life-m0rzfwcau-neontribe.vercel.app/service/[id]) |
|:-:|:-:|
|<a href="https://my-best-life-m0rzfwcau-neontribe.vercel.app/filter">Screenshot of /filter</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/z_EJQBXpTdNjVGFJi1zZYZ_23k8_.png">(view full size)</a> |<a href="https://my-best-life-m0rzfwcau-neontribe.vercel.app/service/[id]">Screenshot of /service/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_Tp9EtQ07roa4ZXdj_pPCD7k8vA_.png">(view full size)</a> |







Commit 6dbc6d5cd40db0bc315c775aea150041ad90af2e (https://my-best-life-m0rzfwcau-neontribe.vercel.app).

**Comment by jthistle** [comment]
@edpe @Nikomus this is now ready for review

**Review by edpe — COMMENTED** [review]
Do we need to prevent the spamming?

**Review by Nikomus — APPROVED** [review]
This is cool 🍞

I think we can prevent the list getting too large by restricting how frequently people can do things that would trigger a notification to appear.

**Comment by jthistle** [comment]
I don't know how we'd prevent the list getting really large - just removing notifications to keep it short would be weird behaviour. I think it'll do for now, and if people want to spam it, then they'll have to deal with the consequences...

**Pull request merged**
