### PR TITLE
feat: make filter stick to bottom of header

### PR DESCRIPTION
**Pull request by Nikomus**
https://trello.com/c/gpE2kuYW/178-making-the-filter-sticky-vv-ee

### CODE REVIEW

**Review by edpe — APPROVED** [review]
looks great - I thought it was going to be more complicated

**Review by rosejbon — APPROVED** [review]
Looks great :)

**Comment by marxian** [comment]
#### 📝Changed routes:


| [**/service/\[id\]**](https://my-best-life-haomwx0qk-neontribe.vercel.app/service/[id]) |
|:-:|
|<a href="https://my-best-life-haomwx0qk-neontribe.vercel.app/service/[id]">Screenshot of /service/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/kbxJq6B-nUGIuNwnPdK9iIoOHuFRTQX44yE_4v6fUtj47d7YF0omUAlfn3LcEgQPXvT43UttUguuUsykX0hYdg.png">(view full size)</a> |







Commit 7fe2cc439d1f5b748e43ce1222250aba93bdc0b6 (https://my-best-life-haomwx0qk-neontribe.vercel.app).

**Comment by Nikomus** [comment]
@edpe @rosejbon This should now be working in combination with the header menu, but I had to make some extra changes to get there.

**Comment by rosejbon** [comment]
> @edpe @rosejbon This should now be working in combination with the header menu, but I had to make some extra changes to get there.

looks great

**Pull request merged**
