### PR TITLE
fix: test not showing anything before showWelcome set

### PR DESCRIPTION
**Pull request by Nikomus**
This is a test!

https://trello.com/c/trIzkMz0/113-upon-navigation-back-to-the-list-the-welcome-view-flashes-up-for-a-split-second-v-e

### CODE REVIEW

**Comment by marxian** [comment]
#### 📝Changed routes:


| [**/**](https://my-best-life-ftkbpxnfa-neontribe.vercel.app/) |
|:-:|
|<a href="https://my-best-life-ftkbpxnfa-neontribe.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_Ql3YaaIYhoBvTU_MWS3dVdl85I_.png">(view full size)</a> |







Commit fc55af958f9a6eb966f32153221b255dc0ddbb0f (https://my-best-life-ftkbpxnfa-neontribe.vercel.app).

**Comment by jthistle** [comment]
This doesn't actually do what you want it to, fixed

**Review by jthistle — APPROVED** [review]
:rocket: :moon:

**Comment by Nikomus** [comment]
Good catch on this actually checking the right thing @jthistle!

**Comment by jthistle** [comment]
fastest merge in the west :upside_down_face:

**Comment by jthistle** [comment]
oh, right, I forgot automerge was a thing

**Pull request merged**
