### PR TITLE
feat: add analytics script

### PR DESCRIPTION
**Pull request by Nikomus**
https://trello.com/c/cgE1WBI7/87-feedback-on-the-app-google-analytics-hotjar-plausible-v-ee

### CODE REVIEW

**Review by jthistle — APPROVED** [review]
Wow, is it that simple? Neat.

**Comment by jthistle** [comment]
(just a note, as I might have expected, my adblocker blocks plausible at the domain level)

**Review by marxian — COMMENTED** [review]
It can be this simple, but I'd recommend the next.js/plausible integration. It avoids potential problems with double-counting views, and makes custom events a pleasure...

https://github.com/4lejandrito/next-plausible

**Comment by marxian** [comment]
@Nikomus Events are flowing to plausible from this deployment.

You can see the effect here: https://plausible.io/share/my-best-life.vercel.app?auth=-8RLOnwnc6CSt05XoKow8

**Comment by Nikomus** [comment]
@Rupert I've carded for next time so we're not too committed if we switch to GA instead. Thank you for the link!

**Pull request merged**
