### PR TITLE
83 ability to choose the first 2 services users see

### PR DESCRIPTION
**Pull request by Nikomus**
https://trello.com/c/DIPyMRJT/83-ability-to-choose-the-first-2-services-users-see-vvv-ee

### CODE REVIEW

**Comment by rosejbon** [comment]
@Nikomus looks good. I can see that the promoted services will appear at the top of the quiz results. Do we want that?

**Comment by Nikomus** [comment]
@rosejbon This should only affect things in the else clause, if the list type is not `listType === 'saved'` or `listType === 'quiz'`

**Review by rosejbon — APPROVED** [review]
:shipit:

**Comment by rosejbon** [comment]
> @rosejbon This should only affect things in the else clause, if the list type is not `listType === 'saved'` or `listType === 'quiz'`

I see now! Sneaky github hiding things :D

**Pull request merged**
