### PR TITLE
feat: add global theme with colours, fonts, reset and defaults

### PR DESCRIPTION
**Pull request by Nikomus**
https://trello.com/c/rWwyyRCL/27-global-styling-setup-vv-ee

A minimal setup for now, that gets the right colours and fonts into the project, and usable by components

### CODE REVIEW

**Review by marxian — APPROVED** [review]
Cool to see a typed theme!

Can you get away with `font-display: swap` maybe?

After that I'm out of expertise in this area :-)

**Comment by Nikomus** [comment]
> Cool to see a typed theme!
> 
> Can you get away with `font-display: swap` maybe?
> 
> After that I'm out of expertise in this area :-)

I hear `font-display: optional;` minimises layout shift from unstyled/invisible fonts. I'll add that now.

**Comment by marxian** [comment]
Ah, that's interesting. I was thinking about the invisible text while fonts are loading. I'm not sure I understand the difference between `optional` and `swap` though...

**Comment by Nikomus** [comment]
As I understand it, `optional` will only wait a very short time to acquire the correct font, and will use a fallback font if it doesn't get it. It won't swap back to the correct font, so no FOUT. You can make sure it does get the correct font in that short time by preloading it.

**Pull request merged**
